services:
  - type: web
    name: task-manager
    env: node
    region: oregon
    plan: free
    buildCommand: |
      cd client
      npm install
      npm run build
      cd ../server
      npm install
    startCommand: node index.js
    rootDir: server
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: <your-mongo-url>
      - key: ANOTHER_KEY
        value: <some-other-env>
